apiVersion: 1

datasources:
  - name: CloudWatch
    uid: cloudwatch
    type: cloudwatch
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      authType: default
      defaultRegion: us-east-1
